name: Semigroups
version: 3.3.0
date: 2020-04-28
description: |
    A package for semigroups and monoids

authors:
    - name: James Mitchell
      url: http://www-groups.mcs.st-andrews.ac.uk/~jamesm/

maintainers:
    - name: James Mitchell
      url: http://www-groups.mcs.st-andrews.ac.uk/~jamesm/

contributors:
    - name: Stuart Burrell
      url: http://sburrell.nfshost.com
    - name: Manuel Delgado
      url: http://cmup.fc.up.pt/cmup/mdelgado/
    - name: James East
      url: http://goo.gl/MuiJu5
    - name: Attila Egri-Nagy
      url: http://www.egri-nagy.hu
    - name: Nicholas Ham
      url: https://n-ham.github.io
    - name: Max Horn
      url: https://www.quendi.de/math
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Julius Jonusas
      url: http://julius.jonusas.work
    - name: Dima V. Pasechnik
      url: http://users.ox.ac.uk/~coml0531/
    - name: Markus Pfeiffer
      url: https://www.morphism.de/~markusp/
    - name: Christopher Russell
      url: mailto:cr66@st-andrews.ac.uk
    - name: Benjamin Steinberg
      url: http://www.sci.ccny.cuny.edu/~benjamin/
    - name: Finn Smith
      url: mailto:fls3@st-andrews.ac.uk
    - name: Jhevon Smith
      url: http://math.sci.ccny.cuny.edu/people?name=Jhevon_Smith
    - name: Michael Torpey
      url: https://mtorpey.github.io
    - name: Murray Whyte
      url: mailto:mw231@st-andrews.ac.uk
    - name: Wilf Wilson
      url: http://wilf.me

GAP: ">=4.9.0"

needed-pkgs:
    - name: "orb"
      version: ">=4.8.2"
      url: "https://gap-packages.github.io/orb"
    - name: "io"
      version: ">=4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "digraphs"
      version: ">=1.0.0"
      url: "https://gap-packages.github.io/Digraphs"
    - name: "genss"
      version: ">=1.6.5"
      url: "https://gap-packages.github.io/genss"
    - name: "images"
      version: ">=1.3.0"
      url: "https://gap-packages.github.io/images/"

suggested-pkgs:
    - name: "gapdoc"
      version: ">=1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/Semigroups
readme: README.md
packageinfo: https://gap-packages.github.io/Semigroups/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/Semigroups/releases/download/v3.3.0/semigroups-3.3.0.tar.gz

abstract: |
    <p>The Semigroups package is a GAP package containing methods for semigroups, monoids, and inverse semigroups.  There are particularly efficient methods for semigroups or ideals consisting of transformations, partial permutations, bipartitions, partitioned binary relations, subsemigroups of regular Rees 0-matrix semigroups, and matrices of various semirings including boolean matrices, matrices over finite fields, and certain tropical matrices.</p><p>Semigroups contains efficient methods for creating semigroups, monoids, and inverse semigroup, calculating their Green's structure, ideals, size, elements, group of units, small generating sets, testing membership, finding the inverses of a regular element, factorizing elements over the generators, and so on. It is possible to test if a semigroup satisfies a particular property, such as if it is regular, simple, inverse, completely regular, and a variety of further properties.</p><p>There are methods for finding presentations for a semigroup, the congruences of a semigroup, the normalizer of a semigroup in a permutation group, the maximal subsemigroups of a finite semigroup, smaller degree partial permutation representations, and the character tables of inverse semigroups. There are functions for producing pictures of the Green's structure of a semigroup, and for drawing graphical representations of certain types of elements.</p>

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
