name: Semigroups
version: "5.5.4"
license: "GPL-3.0-or-later"
date: 2025-08-29
description: |
    A package for semigroups and monoids

authors:
    - name: James Mitchell
      url: https://jdbm.me
    - name: Marina Anagnostopoulou-Merkouri
      url: https://marinaanagno.github.io
    - name: Thomas Breuer
      url: https://www.math.rwth-aachen.de/~Thomas.Breuer/
    - name: Stuart Burrell
      url: https://stuartburrell.github.io
    - name: Reinis Cirpons
      url: https://reinisc.id.lv/
    - name: Tom Conti-Leslie
      url: https://tomcontileslie.com/
    - name: Joseph Edwards
      url: https://github.com/Joseph-Edwards
    - name: Attila Egri-Nagy
      url: http://www.egri-nagy.hu
    - name: Luke Elliott
      url: https://le27.github.io/Luke-Elliott/
    - name: Fernando Flores Brito
      url: mailto:ffloresbrito@gmail.com
    - name: Tillman Froehlich
      url: mailto:trf1@st-andrews.ac.uk
    - name: Nick Ham
      url: https://n-ham.github.io
    - name: Robert Hancock
      url: https://sites.google.com/view/robert-hancock/
    - name: Max Horn
      url: https://www.quendi.de/math
    - name: Christopher Jefferson
      url: https://heather.cafe/
    - name: Julius Jonusas
      url: http://julius.jonusas.work
    - name: Chinmaya Nagpal
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Artemis Konstantinidi
    - name: Hyeokjun Kwon
    - name: Dima V. Pasechnik
      url: http://users.ox.ac.uk/~coml0531/
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/
    - name: Christopher Russell
    - name: Jack Schmidt
      url: https://www.ms.uky.edu/~jack/
    - name: Sergio Siccha
      url: mailto:sergio.siccha@gmail.com
    - name: Finn Smith
      url: https://flsmith.github.io/
    - name: Ben Spiers
    - name: Nicolas Thiéry
      url: https://nicolas.thiery.name/
    - name: Maria Tsalakou
      url: https://mariatsalakou.github.io/
    - name: Chris Wensley
      url: mailto:cdwensley.maths@btinternet.com
    - name: Murray Whyte
      url: mailto:mw231@st-andrews.ac.uk
    - name: Wilf A. Wilson
      url: https://wilf.me
    - name: Tianrun Yang
    - name: Michael Young
      url: https://mtorpey.github.io/
    - name: Fabian Zickgraf
      url: mailto:f.zickgraf@dashdos.com

maintainers:
    - name: James Mitchell
      url: https://jdbm.me

GAP: ">=4.12.1"

needed-pkgs:
    - name: "datastructures"
      version: ">=0.2.5"
      url: "https://gap-packages.github.io/datastructures"
    - name: "digraphs"
      version: ">=1.6.2"
      url: "https://digraphs.github.io/Digraphs"
    - name: "genss"
      version: ">=1.6.5"
      url: "https://gap-packages.github.io/genss"
    - name: "images"
      version: ">=1.3.1"
      url: "https://gap-packages.github.io/images/"
    - name: "IO"
      version: ">=4.5.1"
      url: "https://gap-packages.github.io/io"
    - name: "orb"
      version: ">=4.8.2"
      url: "https://gap-packages.github.io/orb"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">=1.6.3"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "AutoDoc"
      version: ">=2020.08.11"
      url: "https://gap-packages.github.io/AutoDoc"

www: https://semigroups.github.io/Semigroups
readme: README.md
packageinfo: https://semigroups.github.io/Semigroups/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/semigroups/Semigroups/releases/download/v5.5.4/semigroups-5.5.4.tar.gz

abstract: |
    
              The Semigroups package is a GAP package for semigroups, and monoids.
              There are particularly efficient methods for finitely presented
              semigroups and monoids, and for semigroups and monoids consisting of
              transformations, partial permutations, bipartitions, partitioned
              binary relations, subsemigroups of regular Rees 0-matrix semigroups,
              and matrices of various semirings including boolean matrices,
              matrices over finite fields, and certain tropical matrices.
    
              Semigroups contains efficient methods for creating semigroups,
              monoids, and inverse semigroups and monoids, calculating their
              Green's structure, ideals, size, elements, group of units, small
              generating sets, testing membership, finding the inverses of a
              regular element, factorizing elements over the generators, and so on.
              It is possible to test if a semigroup satisfies a particular
              property, such as if it is regular, simple, inverse, completely
              regular, and a large number of further properties.
    
              There are methods for finding presentations for a semigroup, the
              congruences of a semigroup, the maximal subsemigroups of a finite
              semigroup, smaller degree partial permutation representations, and
              the character tables of inverse semigroups. There are functions for
              producing pictures of the Green's structure of a semigroup, and for
              drawing graphical representations of certain types of elements.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    transformation semigroups, partial permutations, inverse semigroups, Green's relations, free inverse semigroup, partition monoid, bipartitions, Rees matrix semigroups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>MABBCCEEEBFHHHJJNKKKPPRSSSSTTWWWYYZ25</span>]   <b class='BibAuthor'>Mitchell, J., Anagnostopoulou-Merkouri, M., Breuer, T., Burrell, S., Cirpons, R., Conti-Leslie, T., Edwards, J., Egri-Nagy, A., Elliott, L., Flores Brito, F., Froehlich, T., Ham, N., Hancock, R., Horn, M., Jefferson, C., Jonusas, J., Nagpal, C., Konovalov, O., Konstantinidi, A., Kwon, H., Pasechnik, D. V., Pfeiffer, M., Russell, C., Schmidt, J., Siccha, S., Smith, F., Spiers, B., Thiéry, N., Tsalakou, M., Wensley, C., Whyte, M., Wilson, W. A., Yang, T., Young, M. and Zickgraf, F.</b>,
     <i class='BibTitle'>Semigroups, A package for semigroups and monoids,
             Version 5.5.4</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://semigroups.github.io/Semigroups">https://semigroups.github.io/Semigroups</a></span>.
    </p>
    

bibtex: |
    @misc{ Semigroups,
      author =           {Mitchell,                    J.                    and
                          Anagnostopoulou\texttt{\symbol{45}}Merkouri,   M.  and
                          Breuer,  T.  and  Burrell,  S.  and  Cirpons,  R.  and
                          Conti\texttt{\symbol{45}}Leslie,  T.  and  Edwards, J.
                          and  Egri\texttt{\symbol{45}}Nagy,  A. and Elliott, L.
                          and  {Flores  Brito}, F. and Froehlich, T. and Ham, N.
                          and  Hancock,  R.  and  Horn, M. and Jefferson, C. and
                          Jonusas,  J.  and  Nagpal,  C.  and  Konovalov, O. and
                          Konstantinidi,  A.  and  Kwon, H. and Pasechnik, D. V.
                          and  Pfeiffer,  M. and Russell, C. and Schmidt, J. and
                          Siccha,   S.   and   Smith,  F.  and  Spiers,  B.  and
                          Thi{\a'e}ry,  N.  and Tsalakou, M. and Wensley, C. and
                          Whyte, M. and Wilson, W. A. and Yang, T. and Young, M.
                          and Zickgraf, F.},
      title =            {{Semigroups},  {A package for semigroups and monoids},
                          {V}ersion 5.5.4},
      month =            {Aug},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href        {https://semigroups.github.io/Semigroups}
                          {\texttt{https://semigroups.github.io/}\discretionary
                          {}{}{}\texttt{Semigroups}}},
      keywords =         {transformation   semigroups;   partial   permutations;
                          inverse  semigroups;  Green's  relations; free inverse
                          semigroup; partition monoid; bipartitions; Rees matrix
                          semigroups},
      printedkey =       {MABBCCEEEBFHHHJJNKKKPPRSSSSTTWWWYYZ25}
    }

