############################################################################
##
#W  conglatt.gi
#Y  Copyright (C) 2016                                   Michael C. Torpey
##
##  Licensing information can be found in the README file of this package.
##
#############################################################################
##
## This file contains functions for a lattice of congruences.
##
## When the congruences of a semigroup are computed, they form a lattice with
## respect to containment.  The information about how the congruences lie in
## this lattice is stored in an IsCongruenceLattice object (a positional object
## based on a list) and can be retrieved from this object with the following
## methods
##
## Most of these methods simply redirect to the first entry of the object, the
## actual list of lists of integers which defines the containments in the
## lattice.  Component 2 in the list is the list of congruences, which is hidden
## when this object is used.

InstallMethod(CongruencesOfLattice,
"for a congruence lattice",
[IsCongruenceLattice],
function(latt)
  return latt![2];
end);

InstallMethod(\[\],
"for a congruence lattice",
[IsCongruenceLattice, IsObject],
function(latt, x)
  return latt![1][x];
end);

InstallMethod(ViewObj,
"for a congruence lattice",
[IsCongruenceLattice],
function(latt)
  ViewObj(latt![1]);
end);

InstallMethod(PrintObj,
"for a congruence lattice",
[IsCongruenceLattice],
function(latt)
  PrintObj(latt![1]);
end);

InstallMethod(Length,
"for a congruence lattice",
[IsCongruenceLattice],
function(latt)
  return Length(latt![1]);
end);

InstallMethod(IsBound\[\],
"for a congruence lattice and a positive integer",
[IsCongruenceLattice, IsPosInt],
function(latt, x)
  return IsBound(latt![1][x]);
end);

###############################################################################
# LatticeOfXCongruences function
###############################################################################
#
# This abstract function takes a semigroup 'S', a string 'type_string' and a
# record 'record'.
# type_string should be in ["Left", "Right", ""] and describes the sort of
# relations we want to find (respectively: left congruences, right congruences,
# two-sided congruences), referred to as 'x congs' below.
# record may contain any of the following components, which should be set to
# 'true' to have the stated effect:
#   * minimal - Return only minimal x-congs
#   * 1gen - Return only x-congs with a single generating pair
#   * restriction - Return only x-congs generated by relating these elements
#
###############################################################################

# FIXME Monolithic functions = BAD!!! JDM

SEMIGROUPS.LatticeOfXCongruences := function(S, type_string, record)
  local report, _XSemigroupCongruence, elms, pairs, total, congs1, nrcongs,
        children, parents, last_collected, nr, pair, badcong, newchildren,
        newparents, newcong, i, c, p, congs, set_func, lattice, join_func,
        length, found, ignore, start, j, k;

  if not IsFinite(S) then
    ErrorNoReturn("Semigroups: SEMIGROUPS.LatticeOfXCongruences: usage,\n",
                  "first argument <S> must be a finite semigroup,");
  fi;

  report :=  SEMIGROUPS.OptionsRec(S).report;
  SEMIGROUPS.OptionsRec(S).report := false;

  _XSemigroupCongruence := EvalString(Concatenation(type_string,
                                                    "SemigroupCongruence"));
  elms := AsListCanonical(S);

  if IsBound(record.restriction) then
    # Only try using pairs from this collection of elements
    pairs := IteratorOfCombinations(AsList(record.restriction), 2);
    total := Binomial(Size(record.restriction), 2);
  else
    # Get all non-reflexive pairs in SxS
    pairs := IteratorOfCombinations(elms, 2);
    total := Binomial(Size(elms), 2);
  fi;

  # Get all the unique 1-generated congs
  Info(InfoSemigroups, 1, "Find congruences with 1 generating pair . . .");
  congs1 := [];     # List of all congs found so far
  nrcongs := 0;     # Number of congs found so far
  children := [];   # List of lists of children
  parents := [];    # List of lists of parents
  last_collected := 0;
  nr := 0;
  for pair in pairs do
    badcong := false;
    newchildren := []; # Children of newcong
    newparents := [];  # Parents of newcong
    newcong := _XSemigroupCongruence(S, pair);
    for i in [1 .. Length(congs1)] do
      if CONG_PAIRS_IN(congs1[i], pair) then 
       #if IsSubrelation(congs1[i], newcong) then
         #if IsSubrelation(newcong, congs1[i]) then
        if CONG_PAIRS_IN(newcong,  congs1[i]!.genpairs[1]) then 
          # This is not a new cong - drop it!
          badcong := true;
          break;
        else
          Add(newparents, i);
        fi;
      #elif IsSubrelation(newcong, congs1[i]) then
      elif CONG_PAIRS_IN(newcong,  congs1[i]!.genpairs[1]) then 
        Add(newchildren, i);
      fi;
    od;
    nr := nr + 1;
    if nr > last_collected + 1999 then 
      if InfoLevel(InfoSemigroups) > 0 then 
        Print("at ", nr, " of ", total, ", found ", nrcongs, " so far\n");
      fi;
      last_collected := nr;
      GASMAN("collect");
    fi;
    if not badcong then
      nrcongs := nrcongs + 1;
      congs1[nrcongs] := newcong;
      children[nrcongs] := newchildren;
      parents[nrcongs] := newparents;
      for c in newchildren do
        Add(parents[c], nrcongs);
      od;
      for p in newparents do
        Add(children[p], nrcongs);
      od;
    fi;
  od;

  congs := ShallowCopy(congs1);
  # We now have all 1-generated congs, which must include all the minimal
  # congs.  We can return if necessary.
  if IsBound(record.minimal) and record.minimal = true then
    # Find all the minimal congs (those with no children)
    congs := congs{Positions(children, [])};
    # Note: we don't include the trivial cong
    # Set the MinimalXCongruencesOfSemigroup attribute
    if not IsBound(record.restriction) then
      set_func := EvalString(Concatenation("SetMinimal",
                                           type_string,
                                           "CongruencesOfSemigroup"));
      set_func(S, congs);
    fi;
    # Minimal congs cannot contain each other
    children := ListWithIdenticalEntries(Length(congs), []);
    lattice := Objectify(NewType(FamilyObj(children),
                                 IsCongruenceLattice),
                         [children, congs]);
    SEMIGROUPS.OptionsRec(S).report := report;
    return lattice;
  elif IsBound(record.1gen) and record.1gen = true then
    # Return the lattice, but don't set any attributes
    lattice := Objectify(NewType(FamilyObj(children),
                                 IsCongruenceLattice),
                         [children, congs]);
    SEMIGROUPS.OptionsRec(S).report := report;
    return lattice;
  fi;

  # Take all their joins
  Info(InfoSemigroups, 1, "Finding joins of 1-generated congruences . . .");
  join_func := EvalString(Concatenation("Join",
                                        type_string,
                                        "SemigroupCongruences"));
  length := 0;
  found := true;
  # 'ignore' is a list of congs that we don't try joining
  ignore := BlistList(congs, []);
  while found do
    # There are new congs to try joining
    start := length + 1;     # New congs start here
    found := false;          # Have we found any more congs on this sweep?
    length := Length(congs); # Remember starting position for next sweep
    for i in [start .. Length(congs)] do # for each new cong
      for j in [1 .. Length(congs1)] do  # for each 1-generated cong
        newcong := join_func(congs[i], congs1[j]);
        badcong := false;  # Is newcong the same as another cong?
        newchildren := []; # Children of newcong
        newparents := [];  # Parents of newcong
        for k in [1 .. Length(congs)] do
          if IsSubrelation(congs[k], newcong) then
            if IsSubrelation(newcong, congs[k]) then
              # This is the same as an old cong - discard it!
              badcong := true;
              break;
            else
              Add(newparents, k);
            fi;
          elif IsSubrelation(newcong, congs[k]) then
            Add(newchildren, k);
          fi;
        od;
        if not badcong then
          nrcongs := nrcongs + 1;
          congs[nrcongs] := newcong;
          children[nrcongs] := newchildren;
          parents[nrcongs] := newparents;
          ignore[nrcongs] := false;
          for c in newchildren do
            Add(parents[c], nrcongs);
          od;
          for p in newparents do
            Add(children[p], nrcongs);
          od;
          found := true;
        fi;
      od;
    od;
  od;

  # Add the trivial cong at the start
  children := Concatenation([[]], children + 1);
  for i in [2 .. nrcongs + 1] do
    Add(children[i], 1, 1);
  od;
  Add(congs, _XSemigroupCongruence(S, []), 1);

  # We have a list of all the congs
  if not IsBound(record.restriction) then
    set_func := EvalString(Concatenation("Set",
                                         type_string,
                                         "CongruencesOfSemigroup"));
    set_func(S, congs);
  fi;

  SEMIGROUPS.OptionsRec(S).report := report;
  # Objectify the result
  lattice := Objectify(NewType(FamilyObj(children),
                               IsCongruenceLattice),
                       [children, congs]);
  return lattice;
end;

InstallMethod(LatticeOfLeftCongruences,
"for a semigroup", [IsSemigroup],
S -> SEMIGROUPS.LatticeOfXCongruences(S, "Left", rec()));

InstallMethod(LatticeOfRightCongruences,
"for a semigroup", [IsSemigroup],
S -> SEMIGROUPS.LatticeOfXCongruences(S, "Right", rec()));

InstallMethod(LatticeOfCongruences,
"for a semigroup", [IsSemigroup],
S -> SEMIGROUPS.LatticeOfXCongruences(S, "", rec()));

InstallMethod(LatticeOfLeftCongruences,
"for a semigroup and a multiplicative element collection",
[IsSemigroup, IsMultiplicativeElementCollection],
function(S, restriction)
  if not ForAll(restriction, x -> x in S) then
    ErrorNoReturn("Semigroups: LatticeOfLeftCongruences: usage,\n",
                  "<restriction> must only contain elements in the <S>");
  fi;
  return SEMIGROUPS.LatticeOfXCongruences(S, "Left",
                                          rec(restriction := restriction));
end);

InstallMethod(LatticeOfRightCongruences,
"for a semigroup and a multiplicative element collection",
[IsSemigroup, IsMultiplicativeElementCollection],
function(S, restriction)
  if not ForAll(restriction, x -> x in S) then
    ErrorNoReturn("Semigroups: LatticeOfRightCongruences: usage,\n",
                  "<restriction> must only contain elements in the <S>");
  fi;
  return SEMIGROUPS.LatticeOfXCongruences(S, "Right",
                                          rec(restriction := restriction));
end);

InstallMethod(LatticeOfCongruences,
"for a semigroup and a multiplicative element collection",
[IsSemigroup, IsMultiplicativeElementCollection],
function(S, restriction)
  if not ForAll(restriction, x -> x in S) then
    ErrorNoReturn("Semigroups: LatticeOfCongruences: usage,\n",
                  "<restriction> must only contain elements in the <S>");
  fi;
  return SEMIGROUPS.LatticeOfXCongruences(S, "",
                                          rec(restriction := restriction));
end);

InstallMethod(LeftCongruencesOfSemigroup,
"for a semigroup", [IsSemigroup],
S -> LatticeOfLeftCongruences(S)![2]);

InstallMethod(RightCongruencesOfSemigroup,
"for a semigroup", [IsSemigroup],
S -> LatticeOfRightCongruences(S)![2]);

InstallMethod(CongruencesOfSemigroup,
"for a semigroup", [IsSemigroup],
S -> LatticeOfCongruences(S)![2]);

InstallMethod(MinimalLeftCongruencesOfSemigroup,
"for a semigroup", [IsSemigroup],
S -> SEMIGROUPS.LatticeOfXCongruences(S, "Left", rec(minimal := true))![2]);

InstallMethod(MinimalRightCongruencesOfSemigroup,
"for a semigroup", [IsSemigroup],
S -> SEMIGROUPS.LatticeOfXCongruences(S, "Right", rec(minimal := true))![2]);

InstallMethod(MinimalCongruencesOfSemigroup,
"for a semigroup", [IsSemigroup],
S -> SEMIGROUPS.LatticeOfXCongruences(S, "", rec(minimal := true))![2]);

InstallMethod(PrincipalLeftCongruencesOfSemigroup,
"for a semigroup", [IsSemigroup],
S -> SEMIGROUPS.LatticeOfXCongruences(S, "Left", rec(1gen := true))![2]);

InstallMethod(PrincipalRightCongruencesOfSemigroup,
"for a semigroup", [IsSemigroup],
S -> SEMIGROUPS.LatticeOfXCongruences(S, "Right", rec(1gen := true))![2]);

InstallMethod(PrincipalCongruencesOfSemigroup,
"for a semigroup", [IsSemigroup],
S -> SEMIGROUPS.LatticeOfXCongruences(S, "", rec(1gen := true))![2]);

InstallMethod(DotString,
"for a congruence lattice",
[IsCongruenceLattice],
function(latt)
  # Call the below function, with info turned off
  return DotString(latt, rec(info := false));
end);

InstallMethod(DotString,
"for a congruence lattice and a record",
[IsCongruenceLattice, IsRecord],
function(latt, opts)
  local congs, S, symbols, i, nr, rel, str, j, k;
  # If the user wants info, then change the node labels
  if opts.info = true then
    # The congruences are stored inside the lattice object
    congs := latt![2];
    S := Range(congs[1]);
    symbols := EmptyPlist(Length(latt));
    for i in [1 .. Length(latt)] do
      nr := NrEquivalenceClasses(congs[i]);
      if nr = 1 then
        symbols[i] := "U";
      elif nr = Size(S) then
        symbols[i] := "T";
      elif IsReesCongruence(congs[i]) then
        symbols[i] := Concatenation("R", String(i));
      else
        symbols[i] := String(i);
      fi;
    od;
  else
    symbols := List([1 .. Length(latt)], String);
  fi;

  rel := List([1 .. Length(latt)], x -> Filtered(latt[x], y -> x <> y));
  str := "";

  if Length(rel) < 40 then
    Append(str, "//dot\ngraph graphname {\n     node [shape=circle]\n");
  else
    Append(str, "//dot\ngraph graphname {\n     node [shape=point]\n");
  fi;

  for i in [1 .. Length(rel)] do
    j := Difference(rel[i], Union(rel{rel[i]}));
    i := symbols[i];
    for k in j do
      k := symbols[k];
      Append(str, Concatenation(i, " -- ", k, "\n"));
    od;
  od;

  Append(str, " }");

  return str;
end);
