###########################################################################
##	<#GAPDoc Label="ClosureSemigroup">
##	<ManSection>
##	<Func Name="ClosureSemigroup" Arg="s, coll"/>
##	<Func Name="ClosureSemigroupNC" Arg="s, coll"/>
##	<Description>
##  creates the semigroup generated by the elements of the transformation
##  semigroup <A>s</A> and the transformation collection or transformation 
##	<A>coll</A>.
##  See <Ref Prop="IsTransformationCollection"/> for more details. <P/>
## 
##	<C>ClosureSemigroup</C> checks that its arguments are a transformation 
##	semigroup and a transformation collection, and then 
##	filters <A>coll</A> to remove any elements in <A>coll</A> that
##	are already in <A>s</A>. 
##  <Example>



##	</Description>
##  </ManSection>
##	<#/GAPDoc>


DeclareGlobalFunction("ClosureSemigroupNC");
DeclareGlobalFunction("ClosureSemigroup");

DeclareGlobalFunction("AddGeneratorsToOrbitsOfImages");
