#############################################################################
##
#W  congruences.gd
#Y  Copyright (C) 2006-2010                             James D. Mitchell
##
##  Licensing information can be found in the README file of this package.
##
#############################################################################
##
## $Id$
##




###########################################################################
##  <#GAPDoc Label="CongruencesSemilattice">
##  <ManSection> 
##  <Attr Name="CongruencesSemilattice" Arg="s"/>
##  </Description><!--JDM example!-->
##  </ManSection>
##	<#/GAPDoc>

DeclareAttribute("CongruencesSemilattice", IsSemigroup);
# the filter here should be IsSemilatticeAsSemigroup but this is undefined
# when this file is read, hence IsSemigroup. 

###########################################################################
##  <#GAPDoc Label="CongruencesSemilatticeByCayleyGraph">
##  <ManSection> 
##  <Func Name="CongruencesSemilatticeByCayleyGraph" Arg="arg"/>
##  </Description><!--JDM example!-->
##  </ManSection>
##	<#/GAPDoc>

DeclareGlobalFunction("CongruencesSemilatticeByCayleyGraph");

###########################################################################
##  <#GAPDoc Label="CongruencesSemilatticeByCayleyGraphNC">
##  <ManSection> 
##  <Func Name="CongruencesSemilatticeByCayleyGraphNC" Arg="elts, cayley, subset, convex, current"/>
##  </Description><!--JDM example!-->
##  </ManSection>
##	<#/GAPDoc>

DeclareGlobalFunction("CongruencesSemilatticeByCayleyGraphNC");


###########################################################################
##  <#GAPDoc Label="ConvexSubsemigroup">
##  <ManSection> 
##  <Func Name="ConvexSubsemigroup" Arg="s, t"/>
##  <Func Name="ConvexSubsemigroupNC" Arg="s, t"/>
##  <Description>
##  returns the least convex subsemigroup of the semilattice <C>s</C> containing ##  the subset <C>t</C> of <C>s</C>. <P/>
##
##  The no check version requires that <C>s</C> is generated by all 
##  of its elements and does not check that <C>s</C> is a semilattice or
##  that <C>t</C> is a subset of <C>s</C>
##  </Description><!--JDM example!-->
##  </ManSection>
##	<#/GAPDoc>

DeclareGlobalFunction("ConvexSubsemigroup");
DeclareGlobalFunction("ConvexSubsemigroupNC");

###########################################################################
##  <#GAPDoc Label="ConvexSubsemigroupByCayleyGraph">
##  <ManSection> 
##  <Func Name="ConvexSubsemigroupByCayleyGraph" Arg="cayley, subset"/>
##  <Description>
##  if <C>cayley</C> is the Cayley graph of a semilattice <C>s</C> generated by 
##  all of its elements and <C>subset</C> is a list of positive integers 
##  corresponding to the positions of a subset of <C>s</C> in 
##  <C>Elements(s)</C>, then <C>ConvexSubsemigroupByCayleyGraph</C> returns a 
##  list of the positions in 
##  <C>Elements(s)</C> of the elements of  the least convex subsemigroup of 
##  <C>s</C> containing <C>Elements(s){subset}</C>.<P/>
## 
##  See also <Ref Func="ConvexSubsemigroup"/>.
##  </Description><!--JDM example!-->
##  </ManSection>
##	<#/GAPDoc>

DeclareGlobalFunction("ConvexSubsemigroupByCayleyGraph");

###########################################################################
##  <#GAPDoc Label="ConvexSubsemigroups">
##  <ManSection> 
##  <Attr Name="ConvexSubsemigroups" Arg="s"/>
##  <Description>
##  </Description><!--JDM example!-->
##  </ManSection>
##	<#/GAPDoc>

DeclareAttribute("ConvexSubsemigroups", IsSemigroup);
# the filter here should be IsSemilatticeAsSemigroup but this is undefined
# when this file is read, hence IsSemigroup. 

###########################################################################
##  <#GAPDoc Label="ConvexSubsemigroupsByCayleyGraph">
##  <ManSection> 
##  <Func Name="ConvexSubsemigroupsByCayleyGraph" Arg="cayley, subset"/>
##  <Description>
##  </Description><!--JDM example!-->
##  </ManSection>
##	<#/GAPDoc>

DeclareGlobalFunction("ConvexSubsemigroupsByCayleyGraph");

###########################################################################
##  <#GAPDoc Label="InfoMonoidCongruences">
##  <ManSection> 
##  <InfoClass Name="InfoMonoidCongruences"/>
##  <Description>
##	This is the InfoClass for the functions in monoid relating to the 
##  computation of congruences of a semigroup. Setting the value 
##	of <C>InfoMonoidAutos</C> to <C>1, 2, 3,</C> or <C>4</C> using the 
##  command <Ref Oper="SetInfoLevel" BookName="ref"/> will give different 
##  levels of information about what <C>GAP</C> is doing during a 
##  computation. 
##  </Description>
##  </ManSection>
##	<#/GAPDoc>

DeclareInfoClass("InfoMonoidCongruences");

###########################################################################
##  <#GAPDoc Label="IsCongruenceOfSemilattice">
##  <ManSection> 
##  <Func Name="IsCongruenceOfSemilattice" Arg="s, p"/>
##  <Description>
##  </Description><!--JDM example!-->
##  </ManSection>
##	<#/GAPDoc>

DeclareGlobalFunction("IsCongruenceOfSemilattice");

###########################################################################
##  <#GAPDoc Label="IsConvexSubsemigpOfSemilattice">
##  <ManSection> 
##  <Func Name="IsConvexSubsemigpOfSemilattice" Arg="s, t"/>
##  <Func Name="IsConvexSubsemigpOfSemilatticeNC" Arg="s, t"/>
##  <Description>
##  returns <C>true</C> if the semigroup <C>t</C> is a convex subsemigroup of 
##  the semilattice <C>s</C>.  A subsemigroup <C>t</C> of a semilattice is 
##	<E>convex</E> if for all <C>x,y</C> in <C>t</C> and for all 
##  <C>z</C> in <C>s</C> if <C>x&lt;z&lt;y</C>, then <C>z</C> in <C>t</C>.</P>
##
##  The no check version requires that <C>s</C> is a semilattice that is 
##  generated by all of its elements, and no check is performed to ensure
##  that <C>s</C> is a semilattice or that <C>t</C> is contained in or 
##  a subsemigroup of <C>s</C>.
##
##  </Description><!--JDM example!-->
##  </ManSection>
##	<#/GAPDoc>

DeclareGlobalFunction("IsConvexSubsemigpOfSemilatticeNC");
DeclareGlobalFunction("IsConvexSubsemigpOfSemilattice");

###########################################################################
##  <#GAPDoc Label="OneMinimalEltSemilatticeByCayleyGraph">
##  <ManSection> 
##  <Func Name="OneMinimalEltSemilatticeByCayleyGraph" Arg="cayley, subset"/>
##  <Description>
##  </Description><!--JDM example!-->
##  </ManSection>
##	<#/GAPDoc>


DeclareGlobalFunction("OneMinimalEltSemilattice");
DeclareGlobalFunction("OneMinimalEltSemilatticeByCayleyGraph");

