name: "Manual"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "stable-*.*"
  schedule:
    # Every day at 3:33 AM UTC
    - cron: '33 3 * * *'

concurrency:
  # Group by workflow and ref; the last component ensures that for pull
  # requests, we limit to one concurrent job, but for the main branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  # Only cancel intermediate pull request builds
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  manual:
    name: "compile and upload manual"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: "Install TeX Live"
        run: |
          packages=(
            texlive-latex-base
            texlive-latex-recommended
            texlive-latex-extra
            texlive-extra-utils
            texlive-fonts-recommended
            texlive-fonts-extra
          )
          sudo apt-get update
          sudo apt-get install "${packages[@]}"
      - uses: gap-actions/setup-gap@v3
      - uses: gap-actions/build-pkg-docs@v2
      - name: "Upload compiled manuals"
        uses: actions/upload-artifact@v4
        with:
          name: "Semigroups manual"
          retention-days: 7
          path: |
            doc/manual.pdf
            doc/*.html
            doc/*.css
            doc/*.js
